<Project Sdk="Microsoft.NET.Sdk.Web">
 <PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>14.0</LangVersion>
		<NoWarn>NU1902</NoWarn>
	  <UserSecretsId>6458f788-00a6-485a-b7e7-9910af9c13d2</UserSecretsId>
  </PropertyGroup>
 <ItemGroup>
   <None Include=".github\copilot-instructions.md" />
 </ItemGroup>

	<ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.74.0" />
		<PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
		<PackageReference Include="Microsoft.SemanticKernel" Version="1.74.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
		<PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.12.0" />
		<PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" Version="1.74.0-alpha" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Migrations\" />
	</ItemGroup>
</Project>